### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by Pillar1989** [Seeed-Studio/Seeed_Arduino_rpcUnified#2]
We welcome requests for new features, and we'll try our best to meet you.  The upcoming features are as follows:
* [x]  mdns
* [ ]  ble mesh
* [x]  Increase the serial port baud rate to over 4M
* [x]  Support Seeeduino XIAO
* [x]  Fix bugs in `WiFi.mode(WIFI_AP_STA);`,(Crashes)
* [x]  Support lwip/pbuf.h
* [ ]  IPv6 support
* [ ]  Synchronize updates to Realtek's official SDK

**Comment by rei-vilo** [comment]
We welcome requests for new features, and we'll try our best to meet you. The upcoming features are as follows:

- [ ]  mdns
- [x]  ble mesh
- [ ]  Increase the serial port baud rate to over 4M
- [x]  Support Seeeduino XIAO

**Comment by Pillar1989** [comment]
@rei-vilo  Aren't you interested in ble mash and XIAO's support?

**Comment by rei-vilo** [comment]
Sorry for the misunderstanding. 

I am mostly interested in BLE mesh and Xiao support, so I set those priorities.

**Comment by ansonhe97** [comment]
We welcome requests for new features, and we'll try our best to meet you.  The upcoming features are as follows:
* [ ]  mdns
* [ ]  ble mesh
* [ ]  Increase the serial port baud rate to over 4M
* [ ]  Support Seeeduino XIAO
* [ ]  Support lwip/pbuf.h
* [ ]  Fix bugs in `WiFi.mode(WIFI_AP_STA);`,(Crashes)
